#!/usr/bin/env python3
import os
import yaml

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    agent_yaml_path = os.path.join(root_dir, 'agent.yaml')
    rules_path = os.path.join(root_dir, '.antigravityrules')

    if not os.path.exists(agent_yaml_path):
        print(f"Error: {agent_yaml_path} does not exist.")
        return

    with open(agent_yaml_path, 'r') as f:
        config = yaml.safe_load(f)

    name = config.get('name', 'ChiefOrchestrator')
    version = config.get('version', '1.0.0')
    model = config.get('model', 'gemini-3-pro')
    instructions = config.get('instructions', '')

    rules_content = f"""# Antigravity Project Rules - Auto-generated from agent.yaml
# DO NOT EDIT THIS FILE DIRECTLY. Edit agent.yaml and run:
#   python3 scripts/sync_agent_rules.py
# or update it using your agent workflows.

## Primary Agent: {name} (v{version})
- **Model:** {model}
- **Role & Instructions:**
{instructions.strip()}

## Autonomous Sub-Agent Rules
When executing tasks in this workspace, the primary agent is authorized to define and spawn the following sub-agents:

"""

    sub_agents = config.get('sub_agents', [])
    for sa in sub_agents:
        sa_name = sa.get('name', 'Unnamed')
        sa_model = sa.get('model', 'gemini-3.5-flash')
        sa_tools = ", ".join(sa.get('tools', []))
        sa_instructions = sa.get('instructions', '').strip()
        rules_content += f"""### Sub-Agent: {sa_name}
- **Model:** {sa_model}
- **Authorized Tools:** [{sa_tools}]
- **Instructions:**
{sa_instructions}

"""

    rules_content += """## Auto-Adoption & Sync Instruction
At the start of every session, the active agent and all sub-agents MUST read `agent.yaml` to dynamically align with the instructions and subagent definitions. If the agent changes the subagent settings or defines new subagents, the agent MUST write those changes to `agent.yaml` and run `python3 scripts/sync_agent_rules.py` to regenerate this `.antigravityrules` file automatically.
"""

    with open(rules_path, 'w') as f:
        f.write(rules_content)

    print(f"Successfully synchronized {agent_yaml_path} to {rules_path}")

if __name__ == '__main__':
    main()
